import env_examples as env

# make_MDP_TP1()
env.make_MDP_TP1()
# make_riverSwim(n_states=6, time_horizon=20)
env.make_riverSwim()
# make_deterministicChain(n_states, time_horizon)
env.make_deterministicChain(6, 20)
# make_stochasticChain(chain_length)
env.make_stochasticChain(10)
# make_bootDQNChain(n_states=6, n_actions=2, time_horizon=15)
env.make_bootDQNChain()
# make_hardBanditMDP(time_horizon, n_actions=2, gap=0.01, pSuccess=0.5)
env.make_hardBanditMDP(10)
# make_stateBanditMDP(stateMul, gap=0.1)
env.make_stateBanditMDP(3)
# make_confidenceMDP(stateMul, gap=0.1)
env.make_confidenceMDP(3)
# make_HconfidenceMDP(time_horizon)
env.make_HconfidenceMDP(10)
# make_GridWold()
GW1 = env.make_GridWold()
